site_name: "Plantilla de talleres"
site_author: "Aula de Software Libre <aulasoftwarelibre@uco.es>"
site_description: "Plantilla para crear documentaci√≥n de los talleres del aula"
site_url: "https://github.com/aulasoftwarelibre/plantilla-talleres"

repo_name: "aulasoftwarelibre/plantilla-talleres"
repo_url: "https://github.com/aulasoftwarelibre/plantilla-talleres"

copyright: Copyleft - CC BY-NC 4.0 - Aula de Software Libre

theme:
  favicon: "images/logoasl.png"
  features:
    - navigation.instant
  icon:
    logo: material/git
  name: "material"
  language: "es"
  palette:
    scheme: slate

plugins:
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - search

extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/aulasoftwarelibre"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/aulasl"
    - icon: fontawesome/brands/facebook
      link: "https://facebook.com/aulasl"
    - icon: fontawesome/brands/instagram
      link: "https://instagram.com/aulasoftwarelibre"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/c/AulaSoftwareLibre"

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list: ~
  - footnotes: ~
  - toc:
      permalink: true
  - pymdownx.keys: ~
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

google_analytics:
  - "UA-51754922-1"
  - "auto"
